[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts-upgradeable/contracts/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

[fuzz]
runs = 10000
depth = 50
max_test_rejects = 13000000

[invariant]
runs = 5000
depth = 50

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
